language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lorey
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: lorey/socials
    python: 3.6
