language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: lorey
  password:
    secure: GTc0gR1MHaDQV8Uah2wZFiJp4QX3L3yqyiMaDs8hBlIPhQJ+A3Cxo62c2TbyuG46DGLK0CLhCZfd5fyNVYS9QRDm6bMZsIBNVE6aKbGLl5ZzmN+C9Mhn2D4ePFl+acQ/k98DIw9qbb2DQGuL3E0ZmL2XbW250P638WSyr2HnaCLkKng99y7ZsK8AwPjhtF9EchxS3rZ36Xl+Zd91x7hTB5tVvUNn3NdRJFZk6iksO1YGQOFDYwprEiB8ToUD3o/7TyqEQa21Iok4v5zYjmavvQKSlMNaQOZx3ts3WxFIt1GdX2eG3IwH+D5C78PCCA8g4BaQTCdeBmG+A1xUyU69fRmrQ0C66NS4yrT6xlYwx2QaXORamp3waQfboiSATljhdRhN39x6/8+/kg6CHrYTk/62X3r0mQ2UTK6HIAt29V0uWQ0nPYssaRaX1H8GiRcCKC9FwYL1Iy7s235ImAW9yeOlHTRmMr0R3qHKoAbnE5kQjRKbuv2wDOebA2NBDMR3UdAHLAE/r0aqolY6Sr442c891dNI4ST3ZPAbQQGfzhhh4mgG1N88F9du+bYT+iise9XITU5KzfxVifAG6Is7PD90dupR56A8EnSBA5ZHpDjG3NcmapavQ/EBhST26GFEQQm/tXfvr/gkBM5ThwdqtbuLFgPMEQkZS7A4pkmrhnI=
  on:
    tags: true
    repo: lorey/socials
    python: 3.6
